// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlc

import (
	"context"
	"time"
)

const enrichEvent = `-- name: EnrichEvent :exec
UPDATE events SET
    url = ?,
    method = ?,
    content_type = ?,
    response_size = ?,
    status_code = ?
WHERE id = ?
`

type EnrichEventParams struct {
	Url          string
	Method       string
	ContentType  string
	ResponseSize int64
	StatusCode   int64
	ID           int64
}

func (q *Queries) EnrichEvent(ctx context.Context, arg EnrichEventParams) error {
	_, err := q.db.ExecContext(ctx, enrichEvent,
		arg.Url,
		arg.Method,
		arg.ContentType,
		arg.ResponseSize,
		arg.StatusCode,
		arg.ID,
	)
	return err
}

const getSpendingByDomain = `-- name: GetSpendingByDomain :many
SELECT
    domain,
    COALESCE(SUM(amount_sat), 0) AS total_sat,
    COALESCE(SUM(fee_sat), 0) AS total_fees,
    COUNT(*) AS payment_count,
    MAX(created_at) AS last_used
FROM events
WHERE status = 'success'
GROUP BY domain
ORDER BY SUM(amount_sat) DESC
`

type GetSpendingByDomainRow struct {
	Domain       string
	TotalSat     interface{}
	TotalFees    interface{}
	PaymentCount int64
	LastUsed     interface{}
}

func (q *Queries) GetSpendingByDomain(ctx context.Context) ([]GetSpendingByDomainRow, error) {
	rows, err := q.db.QueryContext(ctx, getSpendingByDomain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSpendingByDomainRow{}
	for rows.Next() {
		var i GetSpendingByDomainRow
		if err := rows.Scan(
			&i.Domain,
			&i.TotalSat,
			&i.TotalFees,
			&i.PaymentCount,
			&i.LastUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStats = `-- name: GetStats :one
SELECT
    COALESCE(SUM(CASE WHEN status = 'success' THEN amount_sat ELSE 0 END), 0) AS total_spent_sat,
    COALESCE(SUM(CASE WHEN status = 'success' THEN fee_sat ELSE 0 END), 0) AS total_fees_sat,
    COALESCE(SUM(CASE WHEN status = 'success' THEN 1 ELSE 0 END), 0) AS total_payments,
    COALESCE(SUM(CASE WHEN status = 'failed' THEN 1 ELSE 0 END), 0) AS failed_payments,
    COUNT(DISTINCT CASE WHEN status = 'success' THEN domain END) AS domains_accessed
FROM events
`

type GetStatsRow struct {
	TotalSpentSat   interface{}
	TotalFeesSat    interface{}
	TotalPayments   interface{}
	FailedPayments  interface{}
	DomainsAccessed int64
}

func (q *Queries) GetStats(ctx context.Context) (GetStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getStats)
	var i GetStatsRow
	err := row.Scan(
		&i.TotalSpentSat,
		&i.TotalFeesSat,
		&i.TotalPayments,
		&i.FailedPayments,
		&i.DomainsAccessed,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :execlastid
INSERT INTO events (
    domain, url, method, payment_hash, amount_sat,
    fee_sat, status, error_message, duration_ms,
    content_type, response_size, status_code, scheme, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	Domain       string
	Url          string
	Method       string
	PaymentHash  string
	AmountSat    int64
	FeeSat       int64
	Status       string
	ErrorMessage string
	DurationMs   int64
	ContentType  string
	ResponseSize int64
	StatusCode   int64
	Scheme       string
	CreatedAt    time.Time
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertEvent,
		arg.Domain,
		arg.Url,
		arg.Method,
		arg.PaymentHash,
		arg.AmountSat,
		arg.FeeSat,
		arg.Status,
		arg.ErrorMessage,
		arg.DurationMs,
		arg.ContentType,
		arg.ResponseSize,
		arg.StatusCode,
		arg.Scheme,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}
