// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"
)

type Event struct {
	ID           int64
	Domain       string
	Url          string
	Method       string
	PaymentHash  string
	AmountSat    int64
	FeeSat       int64
	Status       string
	ErrorMessage string
	DurationMs   int64
	ContentType  string
	ResponseSize int64
	StatusCode   int64
	CreatedAt    time.Time
}
